controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: fr|es|en

kernel:
    resource: ../../src/Kernel.php
    type: annotation
